broker:
  type: rabbitmq
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_DEFAULT_USER}
  password: ${RABBITMQ_DEFAULT_PASS}
  vhost: ${RABBITMQ_DEFAULT_VHOST}

inputs:
  - type: smtp
    host: ${SMTP_HOST}             # Hostname or IP address of the SMTP server
    port: ${SMTP_PORT}             # Port number
    authentication: true           # Toggle authentication on/off
    auth_type: plain               # Optional: Type of authentication (e.g., "plain", "login")
    username: ${SMTP_USERNAME}     # Global username (optional if per-user credentials are used)
    password: ${SMTP_PASSWORD}     # Global password (optional if per-user credentials are used)
    credentials:                   # Optional: Per-user credentials
      - email: user1@example.com
        password: securepassword123
      - email: user2@example.com
        password: anothersecurepassword
    tls: true                      # Toggle TLS/SSL support

outputs:
  - type: webhook
    url: ${WEBHOOK_URL}