broker:
  type: rabbitmq
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_DEFAULT_USER}
  password: ${RABBITMQ_DEFAULT_PASS}
  vhost: ${RABBITMQ_DEFAULT_VHOST}

inputs:
  - type: smtp
    host: ${SMTP_HOST}             # Hostname or IP address of the SMTP server
    port: ${SMTP_PORT}             # Port number
    authentication: false          # Toggle authentication on/off
    tls: true                      # Toggle TLS/SSL support

outputs:
  - type: webhook
    url: ${WEBHOOK_URL}