services:
  notifystack:
    build:
      context: .
    image: notifystack-dev:latest
    container_name: notifystack-dev
    command: python main.py
    volumes:
      - .:/app  # Mount the local code into the container for live updates
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - rabbitmq
    ports:
      - "587:587"  # Expose SMTP port for testing
    restart: 
      unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # RabbitMQ messaging port
      - "15672:15672"  # RabbitMQ management console
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
